### ISSUE TITLE
hash character in query

### ISSUE THREAD

**Issue by jdevoo** [JeremyGrosser/dewpoint#1]
Hi!
I had some issues with oauth.py while issuing search queries against the Twitter API
I tried quoting the arguments to the search before constructing the query but it still threw 401 errors.
I replaced line 182 in auth.py with
query = map(lambda (k, v): (k, urllib.quote(v)), urlparse.parse_qsl(query))
which helps me go through and successfully issue the request.
I am not sure I fully understand though...
JP

**Comment by JeremyGrosser** [comment]
This library no longer supports oauth and this issue is a decade old. Closing.
